sudo: required
services:
  - docker

before_install:
  - docker build -t eck0/docker-react -f Dockerfile.dev .

script:
  - docker run eck0/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-964107657917'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
